### ISSUE TITLE
Unable to run libmelee due to no dolphin-emu file 

### ISSUE THREAD

**Issue by hasongtran** [altf4/SmashBot#104]
When I try to run both the libmelee command and the example.py command, I get an error, saying "No such file or directory: 'dolphin-emu': 'dolphin-emu'". However, it seems like I installed and built and dolphin correctly, so I'm not sure why I ran into this error. The only reason I could think of is that dolphin-emu is not in my /usr/bin directory and I'm not sure how to get it in there. I'm running this on OS X.

**Comment by altf4** [comment]
It's telling you that because the example.py is trying to run the dolphin command and not finding it. As you said, it's probably because you built it, but didn't _install_ it. 

No worry, you can either install dolphin to your OS's app directory so that programs can find it, or else tell libmelee to expect dolphin to already be running. You can do this in the example.py by commenting out line 45: 

`dolphin.run(render=True)`

Then manually run dolphin yourself, then execute example.py

**Comment by EmersonYe** [comment]
What is the difference between building and installing on MacOS? I built the `memorywatcher-rebased` branch successfully and moved the Dolphin.app binary to my `~/Applications/` folder. However, Dolphin is still saving its configs to `~/Applications/Dolphin.app/Contents/Resources/User/Config/Dolphin.ini`.

I need to explicitly specify the config folder with `~/Applications/Dolphin.app/Contents/MacOS/Dolphin -u ~/Library/Application\ Support/Dolphin` in order to have libmelee find the config files.

Is there more to installing on MacOS than moving the binary to `~/Applications`?

**Comment by altf4** [comment]
I have no idea how Macs work. But maybe you can just link directly to the dolphin binary in libmelee:

https://github.com/altf4/libmelee/blob/master/melee/dolphin.py#L119

Give it the path to your dolphin binary when you run()

**Comment by adriendod** [comment]
> What is the difference between building and installing on MacOS? I built the `memorywatcher-rebased` branch successfully and moved the Dolphin.app binary to my `~/Applications/` folder. However, Dolphin is still saving its configs to `~/Applications/Dolphin.app/Contents/Resources/User/Config/Dolphin.ini`.
> 
> I need to explicitly specify the config folder with `~/Applications/Dolphin.app/Contents/MacOS/Dolphin -u ~/Library/Application\ Support/Dolphin` in order to have libmelee find the config files.
> 
> Is there more to installing on MacOS than moving the binary to `~/Applications`?

Hey, have you find the way for libmelee to find the config files? thanks
