### ISSUE TITLE
Smashbot selects Fox, chooses the level, and does nothing but shine in place.

### ISSUE THREAD

**Issue by someone7070** [altf4/SmashBot#113]
It seems to be functioning fine, except for its very odd behavior. Needless to say, it is trivially easy to beat when it is doing this. Not sure what is wrong. Any ideas?

**Comment by someone7070** [comment]
Here is a link to the debug file. Couldn't upload it here for some reason (says it isn't supported).
https://ufile.io/o54vg7f8

**Comment by altf4** [comment]
Well, the good news is that if SmashBot is multishining in place, that means it can see the gamestate and can press buttons. So it's almost working.

Are you on FD? SmashBot only knows how to play on FD, other stages will make it multishine. Alternatively, are you positive you're using SmashBot, and not the example code in libmelee? (That code will multishine everywhere just as a proof that it's working)

**Comment by someone7070** [comment]
Yes, I am on FD. I'm not sure how I would be ruining just the code associated with libmelee. All I did was download the SmashNot-maser.zip file here from github, follow the instructions (compiling the other Dolphin from source caused a minor error with xlocal.h, which apparently is depreciated as of right now, but the fix was simple), and then run smashbot.py with the command "./smashbot.py" while in the folder. I initially thought I might be able to point it Dolphin file location, but it only seems to work if you actually install the new Dolphin, which I ended up doing.

Based on what you're saying, it does seem I could be running example code, but how is that possible? I was also able to get smashbot.py to change controller port, and to run it in debug mode. Are either of those things possible just running some libmelee example code?

**Comment by altf4** [comment]
Nah, you're definitely not running the libmelee example code.

The dolphin setup is working. You can see in the debug file that smashbot is able to see the gamestate at every frame. In order to do the multishine, it needs to react to the current state. (It doesn't simply spam the correct buttons at the right timing, it actually responds to the gamestate each frame) 

Oh duh. You're probably using an unsupported character. You can see/change the list of supported characters here:

https://github.com/altf4/SmashBot/blob/master/smashbot.py#L115

You can add your character to that list to enable play, but SmashBot won't know how to play against it, really. 

I never did add that to the readme. Damn. I ought to do that.

**Comment by someone7070** [comment]
Yes, that was the issue. Working fine now.
