### ISSUE TITLE
SSBM API

### ISSUE THREAD

**Issue by vladfi1** [altf4/SmashBot#45]
As someone who's interested in trying out different approaches to making a melee AI, it would be cool if there was a something like an API for melee bots (sort of like the BW API), that cpu-level-11 and other bots could share as an interface to the game.

I'm still in the process of going through the code and seeing how easy it would be to achieve this this - one thing that stands out is that the ```GameState``` has a lot of Marth/Fox specific stuff. How easy would it be generalize this to a character-agnostic ```GameState```?

**Comment by altf4** [comment]
There are a few things that are hardcoded right now for sure, but they are all just temporary measures until we get around to generalizing things. For instance, the AI assumes that it is Player 2 and Fox, while the human opponent must be Player 1 and Marth. Obviously, this is not going to be the permanent state of the AI, but it was done that way just to make things easier in order to get real work done.

IE: Solve one problem at a time. I'm trying to make Fox unbeatable in the Fox v Marth matchup and then add new matchups.

As for extensibility... 

I deliberately made the AI with as extensible of a design as I could. It has a 5 tiered hierarchy of goals, so that each one can be hotswapped at any time. 

For instance, if you wanted to make a whole new approach to making a Smash AI because you think mine is wrong and suboptimal, that's great! You could start that by removing all the mid tier goals and writing your own. But the top tier goal is probably the same (Killing your opponent), so that can stay. And the lowest tier goals are probably the same (basic movement and attack chains). It's really only the middle parts that need changing. (Bait, edgeguard, etc...)

It's not an API exactly, but I bet it's as close to one as you're going to get.

**Comment by vladfi1** [comment]
After looking over your code more it actually looks more general than I first thought. I probably won't need to actually do much to GameState or MemoryWatcher. Nice work!

I actually haven't looked too much into your approach, but I think our ultimate goals are a bit different. Namely, I'm not so interested in making an unbeatable AI, but rather a more human-like one, which can play with only human-level reflexes (this can be enforced by adding some frame delay to the computer's actions). I'm also interested in applying modern Reinforcement Learning techniques - [here](http://videolectures.net/rldm2015_silver_reinforcement_learning/) is a good video tutorial.

**Comment by altf4** [comment]
People have asked me about making an AI that "plays like a human", and I've always responded "that sounds hard." :) The difference between how the Level 11 CPU and a human plays is not simply a frame delay in reaction time. My goal with the Level 11 is to be so fast and reliable that it breaks how the game is played. (In much the same way that an aim-bot in a first person shooter plays the game very differently than a human player)

Making a human-like AI would probably require some machine learning techniques. Now that's not crazy, and quite doable. But it's just not the goal of my project at this point in time. I have in the past used the k-nearest-neighbors algorithm to do machine learning, and I could see how it could be applied here too. (The game is basically a giant finite state machine with lots of good heuristics for quality)

In any case, even if you DID want to do machine learning, you probably don't want to go to the hassle of making your AI learn how to wavedash all on its own. Why not bake in the little techniques ahead of time and let the AI deal with "high level" strategy? In that case, the Level 11's code will be very useful to you.

**Comment by altf4** [comment]
I'm gonna call this closed unless you can think of some more specifics in terms of what an API would look like. I like the idea, I'm just not sure what it would look like.
