### ISSUE TITLE
Smashbot doesn't use or recognize items does it?

### ISSUE THREAD

**Issue by briantho** [altf4/SmashBot#74]
With a few items turned on, Hammer, Pokeball, and I forgot what the others were, I was able to fairly easily beat smashbot. I can only assume items are not implemented yet? Could you please put this on a todo list. Thanks

**Comment by altf4** [comment]
No, items have to be disabled. In fact, you should be running with the "Netplay Community Settings" Gecko code that ought to set that sort of thing for you. (The Readme has some info on this) It's also important to apply that Gecko code in order to fix a latency bug. If it's not obvious how to set Gecko codes, I could maybe add a quick guide for that.

Items will probably never be supported, as this is supposed to play with the competitive ruleset as seen in tournament play. (Which does not have items)

**Comment by briantho** [comment]
I already have the netplay code activated, and was still able to put on items. Anyway, so your not going to do items. That's ok, I understand. I Kinda figured the primary focus would be on tournament style rules. NP, that's fine.

**Comment by altf4** [comment]
Some characters like Peach can pull a limited set of items. So there will have to be support for them to a certain extent. But I'm going to close this issue for now as this isn't really something that's on the project roadmap. Keep letting me know if there's anything you think is missing though!
