### ISSUE TITLE
SmashDI: Which direction to go?

### ISSUE THREAD

**Issue by altf4** [altf4/SmashBot#84]
Currently, SmashBot SDI's all hits up and away. This is not ideal and sometimes gets it into trouble. Let's come up with a better heuristic for how to SDI hits in the event that it happens.

**Comment by Eppie** [comment]
Do we have any examples we can try and generalize from? I think starting with a list of "Given scenario X, SDI in direction D" would be helpful. Here's the most obvious one I can think of off the top of my head (if the bot ever starts playing Jigglypuff):

If I am playing Jigglypuff, and the opponent is Fox, and the opponent uses up-air, SDI directly up (in order to avoid the second hit of up-air)

**Comment by spxtr** [comment]
> If I am playing Jigglypuff, and the opponent is Fox, and the opponent uses up-air, SDI directly up (in order to avoid the second hit of up-air)

What if their upwards velocity is high but they're off to the side so that we can SDI to the other side and punish :)

**Comment by altf4** [comment]
I think a good way to start to tackle it is by thinking about what you're trying to accomplish with the SDI. There seem to be a few common uses:

- To escape a multi-hit attack. (Fox's upair or downair)
- To get out out of a combo. (IE: to get out of range of the next attack)
- To survive an attack you wouldn't otherwise survive (get further away from the blast zone)
- To put yourself in a position to tech the hit

With those in mind, one could write some conditions to see which of the four apply, and in which order of priority they should. Then, once you've decided that you should, say, escape a multi-hit attack, what SDI will accomplish that goal? 

(This kind of thinking is basically how SmashBot's hierarchy of goals work)
