### ISSUE TITLE
OSX: Running Libmelee causes Unknown pointer Exception

### ISSUE THREAD

**Issue by edisonhuff** [altf4/SmashBot#91]
After some tinkering to get Smashbot up and running on OSX, I was disappointed to get the following error after starting up Dolphin.

Unknown Pointer 0x10000066 PC 0x8000522c LR 0x00000000

**Comment by altf4** [comment]
What commit of SmashBot are you running?
Also: version of libmelee?

**Comment by edisonhuff** [comment]
I'm building smashbot off the most recent commit of your str branch.
I used pip3 install melee... from what I can see I think its version 0.0.43

**Comment by altf4** [comment]
That error is a dolphin error, it's trying to read from somewhere it can't. Did you build the custom dolphin version that is in the Readme of the str branch? That is the sort of error you'd get for using "vanilla" dolphin. 

If you did build the updated dolphin, you should be able to tell if you're using the right one by going into Dolphin's Help -> About. The version number should look like this:

![image](https://user-images.githubusercontent.com/609563/29752047-7946b178-8b0b-11e7-98d0-099324a4e809.png)

If it doesn't, then you're running the wrong version of dolphin. This is probably because you have "vanilla" dolphin installed, so that when SmashBot starts up dolphin it runs that one. What you can do is manually run the correct version, then start SmashBot with the "-n" flag. That will tell it to not start dolphin, and to expect that it's already running. That ought to work.

**Comment by edisonhuff** [comment]
Thanks! I didn't clone the correct branch of dolphin.

**Comment by DzoYee** [comment]
@altf4 So I'm using 5.0 for other reasons as well as the memory watcher build. But now I get the `Unknown Pointer 0x10000066 PC 0x8000522c LR 0x00000000` error when I run 5.0 even when smashbot and libmelee aren't running. Any tips on how to get 5.0 to work normally again?

**Comment by altf4** [comment]
What **exactly** does the version say? It should look like the screenshot above. (with the branch name and stuff)
