### ISSUE TITLE
Always hit by rollout

### ISSUE THREAD

**Issue by cdubthecoolcat** [altf4/SmashBot#92]
Hi,
I'm able to beat the bot consistently with Jigglypuff by jumping above the stage (the bot doesn't come after me), charging rollout, and hitting the bot until he gets ko'd.

**Comment by altf4** [comment]
Thanks for the bug report! Glad you got everything up and running. 

Rollout is such a weird move... I don't think there's an elegant want to handle it. Probably will just have to be an ugly exception to the rules. Jiggs is not completely inactionable during rollout (she can change directions) in a way that is unlike every other attack.

**Comment by altf4** [comment]
That smash DI is awesome though, right? :)

**Comment by cdubthecoolcat** [comment]
I was thinking the bot could just grab puff out of rollout?  I haven't looked much into the code so I don't really know how it works.

**Comment by altf4** [comment]
That... might actually be possible. My only concern is that Jiggs might be able to turn around in time before the grab comes out. Kinda depends on how the math works out. Not sure yet.

**Comment by Reasel** [comment]
Why not just have a clause for defense to shine her?

**Comment by altf4** [comment]
Does shine outreach rollout? 

Even if it does... the spacing is hard. SmashBot is better at timing than it is spacing. Something with more range like grab, or fsmash would be WAY easier. And you can pivot into it too, so that's easy to do out of a dash dance. 

Honestly, it's not  hard to do, I just haven't spent much time on this lately.
